apiVersion: apps/v1
kind: Deployment
metadata:
  name: hse-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hse-app
  template:
    metadata:
      labels:
        app: hse-app
    spec:
      containers:
        - name: hse-app
          image: harishankarsomasundaram/hse-app:v1
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "2"
      imagePullSecrets:
        - name: hse-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hse-app-service
spec:
  selector:
    app: hse-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31344
  type: NodePort
